IF OBJECT_ID('dbo.Users', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Users (
    UserId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    DisplayName NVARCHAR(120) NULL,
    Email NVARCHAR(320) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;

IF OBJECT_ID('dbo.UserProfiles', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.UserProfiles (
    ProfileId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Goal NVARCHAR(60) NOT NULL,
    Experience NVARCHAR(60) NOT NULL,
    TrainingDays INT NOT NULL,
    EquipmentJson NVARCHAR(MAX) NOT NULL,
    BodyWeightKg DECIMAL(6,2) NULL,
    HeightCm DECIMAL(6,2) NULL,
    TargetWeightKg DECIMAL(6,2) NULL,
    InjuryFlagsJson NVARCHAR(MAX) NOT NULL,
    PreferredSessionLength INT NOT NULL,
    Notes NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_UserProfiles_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF COL_LENGTH('dbo.UserProfiles', 'HeightCm') IS NULL
BEGIN
  ALTER TABLE dbo.UserProfiles ADD HeightCm DECIMAL(6,2) NULL;
END;

IF COL_LENGTH('dbo.UserProfiles', 'TargetWeightKg') IS NULL
BEGIN
  ALTER TABLE dbo.UserProfiles ADD TargetWeightKg DECIMAL(6,2) NULL;
END;

IF OBJECT_ID('dbo.Exercises', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Exercises (
    ExerciseId NVARCHAR(120) NOT NULL PRIMARY KEY,
    Name NVARCHAR(180) NOT NULL,
    MovementPattern NVARCHAR(80) NOT NULL,
    Category NVARCHAR(120) NOT NULL,
    MusclesJson NVARCHAR(MAX) NOT NULL,
    EquipmentJson NVARCHAR(MAX) NOT NULL,
    AvoidWhenJson NVARCHAR(MAX) NOT NULL,
    Cue NVARCHAR(MAX) NOT NULL
  );
END;

IF OBJECT_ID('dbo.WorkoutPlans', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.WorkoutPlans (
    WorkoutPlanId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    SplitName NVARCHAR(120) NOT NULL,
    Summary NVARCHAR(MAX) NOT NULL,
    PlanJson NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_WorkoutPlans_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF OBJECT_ID('dbo.WorkoutDays', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.WorkoutDays (
    WorkoutDayId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    WorkoutPlanId UNIQUEIDENTIFIER NOT NULL,
    DayIndex INT NOT NULL,
    Name NVARCHAR(120) NOT NULL,
    Focus NVARCHAR(240) NOT NULL,
    EstimatedDuration INT NOT NULL,
    DayJson NVARCHAR(MAX) NOT NULL,
    CONSTRAINT FK_WorkoutDays_WorkoutPlans FOREIGN KEY (WorkoutPlanId) REFERENCES dbo.WorkoutPlans(WorkoutPlanId)
  );
END;

IF OBJECT_ID('dbo.WorkoutLogs', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.WorkoutLogs (
    WorkoutLogId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    WorkoutDayId NVARCHAR(120) NOT NULL,
    StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAt DATETIME2 NULL,
    Notes NVARCHAR(MAX) NULL,
    CONSTRAINT FK_WorkoutLogs_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF OBJECT_ID('dbo.SetLogs', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.SetLogs (
    SetLogId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    WorkoutLogId UNIQUEIDENTIFIER NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    ExerciseId NVARCHAR(120) NOT NULL,
    SetNumber INT NOT NULL,
    WeightKg DECIMAL(7,2) NOT NULL,
    Reps INT NOT NULL,
    Effort NVARCHAR(20) NOT NULL,
    Pain BIT NOT NULL DEFAULT 0,
    CompletedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_SetLogs_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF OBJECT_ID('dbo.ReadinessLogs', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ReadinessLogs (
    ReadinessLogId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Energy INT NOT NULL,
    Soreness INT NOT NULL,
    Pain BIT NOT NULL,
    TimeAvailable INT NOT NULL,
    Note NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ReadinessLogs_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF OBJECT_ID('dbo.WeeklyReviews', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.WeeklyReviews (
    WeeklyReviewId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    ReviewText NVARCHAR(MAX) NOT NULL,
    MetricsJson NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_WeeklyReviews_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF OBJECT_ID('dbo.AiEvents', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.AiEvents (
    AiEventId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NULL,
    EventType NVARCHAR(80) NOT NULL,
    Prompt NVARCHAR(MAX) NULL,
    PayloadJson NVARCHAR(MAX) NULL,
    Model NVARCHAR(80) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;

IF OBJECT_ID('dbo.ExerciseSubstitutions', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ExerciseSubstitutions (
    ExerciseSubstitutionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    OriginalExerciseId NVARCHAR(120) NOT NULL,
    ReplacementExerciseId NVARCHAR(120) NOT NULL,
    Reason NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ExerciseSubstitutions_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;

IF OBJECT_ID('dbo.ProgressMetrics', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ProgressMetrics (
    ProgressMetricId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    MetricDate DATE NOT NULL,
    MetricType NVARCHAR(80) NOT NULL,
    MetricValue DECIMAL(12,2) NOT NULL,
    MetadataJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ProgressMetrics_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
  );
END;
